//primusgame\src\constant\varable.js
const admin = {
  id: "primus",
  pass: "11223344",
};

const players = [
  {
    No: 1,
    EmployeeID: "PM00002",
    Fname_Lname: "นางสาว ปิยะนุช พรมประชุม",
    Birthday: "23/10",
  },
  {
    No: 2,
    EmployeeID: "PM00012",
    Fname_Lname: "นาย ไพฑูร พยุงศรี",
    Birthday: "30/04",
  },
  {
    No: 3,
    EmployeeID: "PM00013",
    Fname_Lname: "นาย จีรวัฒน์ เกตุสุวรรณ์",
    Birthday: "13/12",
  },
  {
    No: 4,
    EmployeeID: "PM00017",
    Fname_Lname: "นาย ดุลยภาพ ขันคำ",
    Birthday: "28/10",
  },
  {
    No: 5,
    EmployeeID: "PM00018",
    Fname_Lname: "นาย อุดมพร อยู่แสง",
    Birthday: "10/08",
  },
  {
    No: 6,
    EmployeeID: "PM00023",
    Fname_Lname: "นางสาว รสสุคนธ์ ขำคำ",
    Birthday: "05/04",
  },
  {
    No: 7,
    EmployeeID: "PM00028",
    Fname_Lname: "นาย กิตติศักดิ์ เอี่ยวอ่องพันธ์",
    Birthday: "31/01",
  },
  {
    No: 8,
    EmployeeID: "PM00030",
    Fname_Lname: "นาย ธีรยุทธ ทับทิมดง",
    Birthday: "15/01",
  },
  {
    No: 9,
    EmployeeID: "PM00035",
    Fname_Lname: "นางสาว ไพมณี เวฬุวนารักษ์",
    Birthday: "20/06",
  },
  {
    No: 10,
    EmployeeID: "PM00041",
    Fname_Lname: "นาย อาณัฐชัย ทองพรม",
    Birthday: "16/09",
  },
  {
    No: 11,
    EmployeeID: "PM00044",
    Fname_Lname: "นาย ปรเมษฐ์ อินทร์แก้ว",
    Birthday: "09/11",
  },
  {
    No: 12,
    EmployeeID: "PM00053",
    Fname_Lname: "นางสาว กัญญาณัฐ สีดา",
    Birthday: "27/06",
  },
  {
    No: 13,
    EmployeeID: "PM00073",
    Fname_Lname: "นาย อดิศักดิ์ ฟักเครือ",
    Birthday: "18/09",
  },
  {
    No: 14,
    EmployeeID: "PM00092",
    Fname_Lname: "นาย บัณฑิต บุษบงค์",
    Birthday: "23/03",
  },
  {
    No: 15,
    EmployeeID: "PM00101",
    Fname_Lname: "นาย เอกชัย หาญประสิทธิ์ธาดา",
    Birthday: "02/08",
  },
  {
    No: 16,
    EmployeeID: "PM00112",
    Fname_Lname: "นางสาว รณพร สอนฤทธิ์",
    Birthday: "17/05",
  },
  {
    No: 17,
    EmployeeID: "PM00132",
    Fname_Lname: "นาย ฉัตรชัย เหรวรรณ์",
    Birthday: "07/05",
  },
  {
    No: 18,
    EmployeeID: "PM00133",
    Fname_Lname: "นางสาว นิตยา อุตมะ",
    Birthday: "10/01",
  },
  {
    No: 19,
    EmployeeID: "PM00174",
    Fname_Lname: "นางสาว ขนิษฐา ไชยดี",
    Birthday: "07/07",
  },
  {
    No: 20,
    EmployeeID: "PM00176",
    Fname_Lname: "นาย จิตติ อินหงษา",
    Birthday: "02/06",
  },
  {
    No: 21,
    EmployeeID: "PM00206",
    Fname_Lname: "นาย ฉลองบุญ ขจรนาถ",
    Birthday: "13/04",
  },
  {
    No: 22,
    EmployeeID: "PM00207",
    Fname_Lname: "นาย ทนงศักดิ์ จัดเขตรกรรม",
    Birthday: "22/04",
  },
  {
    No: 23,
    EmployeeID: "PM00277",
    Fname_Lname: "นาย ต่อศักดิ์ เขตขุนทด",
    Birthday: "08/06",
  },
  {
    No: 24,
    EmployeeID: "PM00300",
    Fname_Lname: "นาย ศาโรจน์ ปานแย้ม",
    Birthday: "24/11",
  },
  {
    No: 25,
    EmployeeID: "PM00301",
    Fname_Lname: "นาย ชัยรัตน์ ปานแย้ม",
    Birthday: "26/10",
  },
  {
    No: 26,
    EmployeeID: "PM00302",
    Fname_Lname: "นาย รุ่งโรจน์ ขำคำ",
    Birthday: "10/05",
  },
  {
    No: 27,
    EmployeeID: "PM00304",
    Fname_Lname: "นางสาว จุราพร เกษาอาด",
    Birthday: "13/09",
  },
  {
    No: 28,
    EmployeeID: "PM00305",
    Fname_Lname: "นาย ณัฐพล ปิจดี",
    Birthday: "09/09",
  },
  {
    No: 29,
    EmployeeID: "PM00306",
    Fname_Lname: "นางสาว เกษร น้อยจาก",
    Birthday: "21/12",
  },
  {
    No: 30,
    EmployeeID: "PM00307",
    Fname_Lname: "นางสาว พรพรรณ บุญเรือง",
    Birthday: "17/12",
  },
  {
    No: 31,
    EmployeeID: "PM00308",
    Fname_Lname: "นางสาว พิศมัย แก้วไซเนียม",
    Birthday: "04/03",
  },
  {
    No: 32,
    EmployeeID: "PM00309",
    Fname_Lname: "นางสาว ทิพวรรณ สุขสำราญ",
    Birthday: "10/03",
  },
  {
    No: 33,
    EmployeeID: "PM00311",
    Fname_Lname: "นาย ณัฐวุฒิ โพนามาศ",
    Birthday: "02/01",
  },
  {
    No: 34,
    EmployeeID: "PM00312",
    Fname_Lname: "นางสาว จิราพร การะโภชน์",
    Birthday: "30/05",
  },
  {
    No: 35,
    EmployeeID: "PM00313",
    Fname_Lname: "นางสาว เสาวรัตน์ จารี",
    Birthday: "19/08",
  },
  {
    No: 36,
    EmployeeID: "PM00314",
    Fname_Lname: "นางสาว อุมา ผิวอ่อน",
    Birthday: "06/04",
  },
  {
    No: 37,
    EmployeeID: "PM00315",
    Fname_Lname: "นาย ประพันธ์ หมีไข่",
    Birthday: "17/12",
  },
  {
    No: 38,
    EmployeeID: "PM00316",
    Fname_Lname: "นางสาว ลักขณา แก้วเวียง",
    Birthday: "16/12",
  },
  {
    No: 39,
    EmployeeID: "PM00317",
    Fname_Lname: "นางสาว มาลัย สุขอร่าม",
    Birthday: "03/08",
  },
  {
    No: 40,
    EmployeeID: "PM00318",
    Fname_Lname: "นาย จำรัส บุญอ่อง",
    Birthday: "09/06",
  },
  {
    No: 41,
    EmployeeID: "PM00320",
    Fname_Lname: "นาย อัศนี สียา",
    Birthday: "25/10",
  },
  {
    No: 42,
    EmployeeID: "PM00321",
    Fname_Lname: "นาย พิเชษฐ เกษแจ่ม",
    Birthday: "24/11",
  },
  {
    No: 43,
    EmployeeID: "PM00322",
    Fname_Lname: "นาย พงษ์พันธ์ สีดา",
    Birthday: "18/12",
  },
  {
    No: 44,
    EmployeeID: "PM00323",
    Fname_Lname: "นาย สุวิทย์ พูมน",
    Birthday: "18/01",
  },
  {
    No: 45,
    EmployeeID: "PM00324",
    Fname_Lname: "นาย อภิชาติ เกษแจ่ม",
    Birthday: "08/01",
  },
  {
    No: 46,
    EmployeeID: "PM00325",
    Fname_Lname: "นาย ธนกร บุตรเพียร",
    Birthday: "04/05",
  },
  {
    No: 47,
    EmployeeID: "PM00326",
    Fname_Lname: "นาย สุรสิทธิ์ สงคราม",
    Birthday: "07/11",
  },
  {
    No: 48,
    EmployeeID: "PM00327",
    Fname_Lname: "นาย ทรงพล แก้วดู",
    Birthday: "12/12",
  },
  {
    No: 49,
    EmployeeID: "PM00330",
    Fname_Lname: "นาย นคร ตรีสิงหวงศ์",
    Birthday: "15/07",
  },
  {
    No: 50,
    EmployeeID: "PM00331",
    Fname_Lname: "นางสาว นันทิตา ธรรมนู",
    Birthday: "30/06",
  },
  {
    No: 51,
    EmployeeID: "PM00332",
    Fname_Lname: "นาย พุทธิกร พิพัฒน์ไพศาล",
    Birthday: "16/11",
  },
  {
    No: 52,
    EmployeeID: "PM00334",
    Fname_Lname: "นาย ธีรพงษ์ ปานทุ่ง",
    Birthday: "19/02",
  },
  {
    No: 53,
    EmployeeID: "PM00335",
    Fname_Lname: "นางสาว นุชนาท แสงจันทร์",
    Birthday: "30/12",
  },
  {
    No: 54,
    EmployeeID: "PM00336",
    Fname_Lname: "นาย ทนง ปิยะอารมณ์รัตน์",
    Birthday: "29/01",
  },
  {
    No: 55,
    EmployeeID: "PM00337",
    Fname_Lname: "นางสาว ณัฐริณีย์ หลุ่มบุญเรือง",
    Birthday: "08/03",
  },
  {
    No: 56,
    EmployeeID: "PM00338",
    Fname_Lname: "นาย สุพจน์ จันทร์หยวก",
    Birthday: "05/04",
  },
  {
    No: 57,
    EmployeeID: "PM00340",
    Fname_Lname: "นาย พรชัย กิมิพันธ์",
    Birthday: "25/06",
  },
  {
    No: 58,
    EmployeeID: "PM00341",
    Fname_Lname: "นาย กรรตภณ ผู้กำจัด",
    Birthday: "04/08",
  },
  {
    No: 59,
    EmployeeID: "PM00342",
    Fname_Lname: "นาย สุพจน์ ราวิน",
    Birthday: "11/03",
  },
  {
    No: 60,
    EmployeeID: "PM00344",
    Fname_Lname: "นางสาว สุภาภรณ์ จันทร์พรมมา",
    Birthday: "14/06",
  },
  {
    No: 61,
    EmployeeID: "PM00345",
    Fname_Lname: "นางสาว นัญรัตน์ คงสุข",
    Birthday: "02/06",
  },
  {
    No: 62,
    EmployeeID: "PM00346",
    Fname_Lname: "นาย เกียรติศักดิ์ แก้วเขียว",
    Birthday: "07/07",
  },
  {
    No: 63,
    EmployeeID: "PM00347",
    Fname_Lname: "นางสาว กาญจนา พลเสนา",
    Birthday: "03/01",
  },
  {
    No: 64,
    EmployeeID: "PM00349",
    Fname_Lname: "นาย พงษ์สิทธิ์ ศรสวาท",
    Birthday: "04/08",
  },
  {
    No: 65,
    EmployeeID: "PM00350",
    Fname_Lname: "นางสาว พิจิตรา เกตุเพ็ชร",
    Birthday: "13/10",
  },
  {
    No: 66,
    EmployeeID: "PM00351",
    Fname_Lname: "นางสาว วิจิตรา อาจประจักร์",
    Birthday: "28/09",
  },
  {
    No: 67,
    EmployeeID: "PM00352",
    Fname_Lname: "นาย คมกล้า รัตนพรมรินทร์",
    Birthday: "19/11",
  },
  {
    No: 68,
    EmployeeID: "PM00353",
    Fname_Lname: "นาย วชิรวิทย์ ศรีถา",
    Birthday: "16/01",
  },
  {
    No: 69,
    EmployeeID: "PM00355",
    Fname_Lname: "นาย ทศวรรษ ทิพย์ประจิตต์",
    Birthday: "27/01",
  },
  {
    No: 70,
    EmployeeID: "PM00356",
    Fname_Lname: "นาย ธนธรณ์ โต๊ะซำ",
    Birthday: "02/09",
  },
  {
    No: 71,
    EmployeeID: "PM00357",
    Fname_Lname: "นาย ณัฐภูมิ ทองด้วง",
    Birthday: "17/06",
  },
  {
    No: 72,
    EmployeeID: "PM00362",
    Fname_Lname: "นาย ภานุมาศ รัตนะ",
    Birthday: "20/06",
  },
  {
    No: 73,
    EmployeeID: "PM00381",
    Fname_Lname: "นาย สุทธิพงศ์ ยงยุทธ์",
    Birthday: "08/01",
  },
  {
    No: 74,
    EmployeeID: "PM00382",
    Fname_Lname: "นาย นัฐพงษ์ จุลโยธา",
    Birthday: "06/04",
  },
  {
    No: 75,
    EmployeeID: "PM00383",
    Fname_Lname: "นางสาว กิติยา สุปัตติ",
    Birthday: "15/07",
  },
  {
    No: 76,
    EmployeeID: "PM00386",
    Fname_Lname: "นาย สมชาย ท่อนทอง",
    Birthday: "28/11",
  },
  {
    No: 77,
    EmployeeID: "PM00387",
    Fname_Lname: "นางสาว สาวลักษณ์ ประกอบแสง",
    Birthday: "07/11",
  },
  {
    No: 78,
    EmployeeID: "PM00388",
    Fname_Lname: "นาย อำนาจ ดีเฉลา",
    Birthday: "07/01",
  },
  {
    No: 79,
    EmployeeID: "PM00391",
    Fname_Lname: "นาย ปัฐยาวัต อินสุข",
    Birthday: "03/08",
  },
  {
    No: 80,
    EmployeeID: "PM00393",
    Fname_Lname: "นาย ทรงวุฒิ แก้วดู",
    Birthday: "05/12",
  },
  {
    No: 81,
    EmployeeID: "PM00394",
    Fname_Lname: "นาย ธนากร อุตมะ",
    Birthday: "15/11",
  },
  {
    No: 82,
    EmployeeID: "PM00396",
    Fname_Lname: "นาย ธนกฤต นนท์กระโทก",
    Birthday: "27/04",
  },
  {
    No: 83,
    EmployeeID: "PM00397",
    Fname_Lname: "นาย พลวิชญ์ ขวัญสุข",
    Birthday: "25/04",
  },
  {
    No: 84,
    EmployeeID: "PM00398",
    Fname_Lname: "นาย เฉลิมชัย จิตรีรมณ์",
    Birthday: "18/09",
  },
  {
    No: 85,
    EmployeeID: "PM00399",
    Fname_Lname: "นาย ประวิทย์ พลเสนา",
    Birthday: "20/02",
  },
  {
    No: 86,
    EmployeeID: "PM00400",
    Fname_Lname: "นาย ภูมิมินทร์ อังคณิต",
    Birthday: "03/02",
  },
  {
    No: 87,
    EmployeeID: "PM00401",
    Fname_Lname: "นาย ชัยวัฒน์ มูลตรีศรี",
    Birthday: "05/09",
  },
  {
    No: 88,
    EmployeeID: "PM00403",
    Fname_Lname: "นาย ปรีชา พานแก้ว",
    Birthday: "10/03",
  },
  {
    No: 89,
    EmployeeID: "THT0002",
    Fname_Lname: "นาย คัมภีร์ แก้วบัลลัง",
    Birthday: "29/09",
  },
  {
    No: 90,
    EmployeeID: "THT0005",
    Fname_Lname: "นาย กวินภพ เขียววงษ์",
    Birthday: "09/02",
  },
  {
    No: 91,
    EmployeeID: "THT0006",
    Fname_Lname: "นาย นิติพงษ์ มณีรุ่ง",
    Birthday: "23/05",
  },
  {
    No: 92,
    EmployeeID: "THT0007",
    Fname_Lname: "นาย นิติพนธิ์ มณีรุ่ง",
    Birthday: "23/05",
  },
  {
    No: 93,
    EmployeeID: "THT0010",
    Fname_Lname: "นางสาว มณฑิรา บุษบก",
    Birthday: "19/02",
  },
  {
    No: 94,
    EmployeeID: "THT0011",
    Fname_Lname: "นาย สถาพร รัตนประเสริฐ",
    Birthday: "11/10",
  },
  {
    No: 95,
    EmployeeID: "THT0012",
    Fname_Lname: "นางสาว สุวพัชร สุทธิจักษ์",
    Birthday: "23/09",
  },
  {
    No: 96,
    EmployeeID: "THT0013",
    Fname_Lname: "นาย พิทักษ์ชัย พิทักษ์สุวรา",
    Birthday: "22/11",
  },
  {
    No: 97,
    EmployeeID: "THT0014",
    Fname_Lname: "นาย นฤเบศร์ สุขสุถ้อย",
    Birthday: "19/04",
  },
  {
    No: 98,
    EmployeeID: "THT0015",
    Fname_Lname: "นาย วิรุณ ผ่านจังหาร",
    Birthday: "04/11",
  },
  {
    No: 99,
    EmployeeID: "THT0018",
    Fname_Lname: "นางสาว จรรยา ประสิทธิ์เกษกัน",
    Birthday: "24/06",
  },
  {
    No: 100,
    EmployeeID: "THT0020",
    Fname_Lname: "นางสาว เอมอร นามพันธ์",
    Birthday: "12/09",
  },
  {
    No: 101,
    EmployeeID: "THT0024",
    Fname_Lname: "นางสาว เพ็ญพักตร์ ฝ้ายป่าน",
    Birthday: "18/03",
  },
  {
    No: 102,
    EmployeeID: "THT0025",
    Fname_Lname: "นาย ธีระภัทร มีแก้ว",
    Birthday: "27/08",
  },
  {
    No: 103,
    EmployeeID: "THT0030",
    Fname_Lname: "นาย วรภพ สุขวงศ์",
    Birthday: "15/02",
  },
  {
    No: 104,
    EmployeeID: "THT0036",
    Fname_Lname: "นาย ภัทรศักดิ์ หอมดี",
    Birthday: "29/04",
  },
  {
    No: 105,
    EmployeeID: "THT0050",
    Fname_Lname: "นางสาว เกศินี โพธิ์กระจ่าง",
    Birthday: "15/11",
  },
  {
    No: 106,
    EmployeeID: "THT0052",
    Fname_Lname: "นาง นิรวดี บุญเจริญ",
    Birthday: "19/11",
  },
  {
    No: 107,
    EmployeeID: "THT0053",
    Fname_Lname: "นางสาว จุฬาลักษณ์ ทรัพย์ประเสริฐ",
    Birthday: "01/02",
  },
  {
    No: 108,
    EmployeeID: "THT0054",
    Fname_Lname: "นางสาว นิภาภรณ์ แสงวงค์",
    Birthday: "28/10",
  },
  {
    No: 109,
    EmployeeID: "THT0055",
    Fname_Lname: "นาย สมพงษ์ ทรัพย์ประเสริฐ",
    Birthday: "29/05",
  },
  {
    No: 110,
    EmployeeID: "THT0056",
    Fname_Lname: "นาย ถาวร แป้นวงษ์",
    Birthday: "15/12",
  },
  {
    No: 111,
    EmployeeID: "THT0057",
    Fname_Lname: "นางสาว นวลละออง แสวงสิน",
    Birthday: "14/06",
  },
  {
    No: 112,
    EmployeeID: "THT0060",
    Fname_Lname: "นาย อิทธิพล จูฑะพันธุ์",
    Birthday: "22/09",
  },
  {
    No: 113,
    EmployeeID: "THT0064",
    Fname_Lname: "นางสาว อรัญญา จำรัสฉาย",
    Birthday: "12/12",
  },
  {
    No: 114,
    EmployeeID: "THT0068",
    Fname_Lname: "นาย ธวัชชัย ช่วยตา",
    Birthday: "24/08",
  },
  {
    No: 115,
    EmployeeID: "THT0069",
    Fname_Lname: "นาย จิรายุ เกตุสุวรรณ์",
    Birthday: "28/04",
  },
  {
    No: 116,
    EmployeeID: "THT0070",
    Fname_Lname: "นางสาว จิราวรรณ ทิพรอด",
    Birthday: "09/07",
  },
  {
    No: 117,
    EmployeeID: "THT0072",
    Fname_Lname: "นางสาว จุฑามาศ ใช้อู๋",
    Birthday: "13/06",
  },
  {
    No: 118,
    EmployeeID: "THT0073",
    Fname_Lname: "นางสาว ยุพาทิพย์ ผลรัก",
    Birthday: "30/10",
  },
  {
    No: 119,
    EmployeeID: "THT0074",
    Fname_Lname: "นางสาว สุจินดา แรงกสิวิทย์",
    Birthday: "01/11",
  },
  {
    No: 120,
    EmployeeID: "THT0075",
    Fname_Lname: "นาย นัฐดนัย บำรุงรักษ์",
    Birthday: "16/01",
  },
  {
    No: 121,
    EmployeeID: "THT0076",
    Fname_Lname: "นาย วิวัฒน์ สืบศรี",
    Birthday: "15/10",
  },
  {
    No: 122,
    EmployeeID: "THT0078",
    Fname_Lname: "นางสาว ภัทริดา กองบุญมา",
    Birthday: "25/03",
  },
  {
    No: 123,
    EmployeeID: "THT0079",
    Fname_Lname: "นาง บุสิตา พิพัฒน์ไพศาล",
    Birthday: "07/05",
  },
  {
    No: 124,
    EmployeeID: "THT0080",
    Fname_Lname: "นาย นพดล คำสุก",
    Birthday: "26/08",
  },
  {
    No: 125,
    EmployeeID: "THT0081",
    Fname_Lname: "นาย วิรัช กิมิพันธ์",
    Birthday: "03/02",
  },
  {
    No: 126,
    EmployeeID: "THT0082",
    Fname_Lname: "นางสาว หญิง ดวงแก้ว",
    Birthday: "04/02",
  },
  {
    No: 127,
    EmployeeID: "THT0083",
    Fname_Lname: "นาย พงศกร โพธิจาด",
    Birthday: "06/02",
  },
  {
    No: 128,
    EmployeeID: "THT0084",
    Fname_Lname: "นางสาว ภรณ์ทิพย์ ดีดาร์",
    Birthday: "26/12",
  },
  {
    No: 129,
    EmployeeID: "THT0085",
    Fname_Lname: "นาย วีระ แก้วสม",
    Birthday: "04/12",
  },
  {
    No: 130,
    EmployeeID: "THT0088",
    Fname_Lname: "นาย ภานุพัฒน์ เกษมุติ",
    Birthday: "08/10",
  },
  {
    No: 131,
    EmployeeID: "THT0089",
    Fname_Lname: "นาย ภูสิทธิ์ ฉันชะนิด",
    Birthday: "28/04",
  },
  {
    No: 132,
    EmployeeID: "THT0090",
    Fname_Lname: "นาย วีระศักดิ์ ทองหมู่",
    Birthday: "18/11",
  },
  {
    No: 133,
    EmployeeID: "THT0091",
    Fname_Lname: "นางสาว นิษา คงแก้ว",
    Birthday: "26/07",
  },
  {
    No: 134,
    EmployeeID: "THT0092",
    Fname_Lname: "นาย ภาณุวัฒน์ สงวนดิษ",
    Birthday: "16/07",
  },
  {
    No: 135,
    EmployeeID: "THT0093",
    Fname_Lname: "นาย วิชิต เข็มเพ็ชร",
    Birthday: "22/10",
  },
  {
    No: 136,
    EmployeeID: "THT0094",
    Fname_Lname: "นาย วันชาติ สุวรรณไตรย์",
    Birthday: "25/01",
  },
  {
    No: 137,
    EmployeeID: "THT0095",
    Fname_Lname: "นาย เดชา แดงอ่อน",
    Birthday: "01/11",
  },
  {
    No: 138,
    EmployeeID: "THT0096",
    Fname_Lname: "นาย สมพร อังคณิต",
    Birthday: "12/08",
  },
  {
    No: 139,
    EmployeeID: "THT0097",
    Fname_Lname: "นาย พสธร บูลวิบูรณ์",
    Birthday: "27/01",
  },
  {
    No: 140,
    EmployeeID: "THT0098",
    Fname_Lname: "นาย เพชรนิยม อังคณิต",
    Birthday: "21/09",
  },
  {
    No: 141,
    EmployeeID: "THT0099",
    Fname_Lname: "นาย อดิศร มาตรพันธ์นา",
    Birthday: "11/10",
  },
  {
    No: 142,
    EmployeeID: "THT0101",
    Fname_Lname: "นาย รวิภาส ชูทรัพย์",
    Birthday: "30/11",
  },
  {
    No: 143,
    EmployeeID: "THT0102",
    Fname_Lname: "นาย พัฒนา ชมจันทร์",
    Birthday: "23/08",
  },
  {
    No: 144,
    EmployeeID: "THT0103",
    Fname_Lname: "นางสาว ธัญสุดา คุ้มสา",
    Birthday: "14/11",
  },
  {
    No: 145,
    EmployeeID: "THT0104",
    Fname_Lname: "นางสาว ณัฐติยา พันธ์เพ็ง",
    Birthday: "10/10",
  },
  {
    No: 146,
    EmployeeID: "THT0107",
    Fname_Lname: "นาย วิศรุต ยิ่งศักดา",
    Birthday: "13/11",
  },
  {
    No: 147,
    EmployeeID: "THT0108",
    Fname_Lname: "นาย ตะวัน บุดศรี",
    Birthday: "15/02",
  },
  {
    No: 148,
    EmployeeID: "THT0109",
    Fname_Lname: "นางสาว สุมนัสชนก เอื้อจิตร์",
    Birthday: "03/05",
  },
  {
    No: 149,
    EmployeeID: "THT0110",
    Fname_Lname: "นางสาว ขวัญนภา เดชศรี",
    Birthday: "10/09",
  },
  {
    No: 150,
    EmployeeID: "THT0111",
    Fname_Lname: "นาย ธัชพล ข่ายทอง",
    Birthday: "31/08",
  },
  {
    No: 151,
    EmployeeID: "THT0114",
    Fname_Lname: "นาย ปภาวินท์ ภิรมย์ชลทรัพย์",
    Birthday: "20/11",
  },
  {
    No: 152,
    EmployeeID: "THT0117",
    Fname_Lname: "นางสาว สุพรรษา แสงล้ำ",
    Birthday: "29/06",
  },
  {
    No: 153,
    EmployeeID: "THT0121",
    Fname_Lname: "นางสาว อัสมีรา เจ๊ะนิ",
    Birthday: "02/08",
  },
  {
    No: 154,
    EmployeeID: "THT0123",
    Fname_Lname: "นาย ณรงฤทธิ์ จิบหนองแวง",
    Birthday: "29/09",
  },
  {
    No: 155,
    EmployeeID: "THT0124",
    Fname_Lname: "นางสาว อังคณา รัตนพรมรินทร์",
    Birthday: "26/09",
  },
  {
    No: 156,
    EmployeeID: "THT0126",
    Fname_Lname: "นาย สหรัฐ มณีจันทร์",
    Birthday: "04/12",
  },
  {
    No: 157,
    EmployeeID: "THT0130",
    Fname_Lname: "นาย วีระยุทธ พืชผักหวาน",
    Birthday: "12/04",
  },
  {
    No: 158,
    EmployeeID: "THT0131",
    Fname_Lname: "นาย ณัฐนัน กลิ่นขำ",
    Birthday: "08/11",
  },
  {
    No: 159,
    EmployeeID: "THT0132",
    Fname_Lname: "นางสาว เจนจิรา เขตขุนทด",
    Birthday: "22/12",
  },
  {
    No: 160,
    EmployeeID: "THT0133",
    Fname_Lname: "นาย วิรชัย ศรีหนองโป่ง",
    Birthday: "06/11",
  },
  {
    No: 161,
    EmployeeID: "THT0134",
    Fname_Lname: "นาย จิรเดช นาคสินธุ์",
    Birthday: "26/11",
  },
];
//
const rewardCountGame1 = {
  Reward1: 50,
  Reward2: 50,
  Reward3: 61,
};

export { admin, players, rewardCountGame1 };
